In [ ]:
!nvidia-smi

Tue Feb 28 16:57:28 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P0    26W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 00. Pytorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


##Introducting Tensors

###Creating Tensors

In [ ]:
#Scalar
scalar  = torch.tensor(7);scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7]);vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
matrix = torch.tensor([[7,8,8],
                      [9,10,6],
                      [11,12,13]])
matrix

tensor([[ 7,  8,  8],
        [ 9, 10,  6],
        [11, 12, 13]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 9, 10,  6])

In [ ]:
matrix.shape

torch.Size([3, 3])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                         [3,4,5],
                         [8,5,6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape #existe 1 tensor com 3 x 3 elementos

torch.Size([1, 3, 3])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[[1,2,3,5],
                         [3,4,5,5],
                         [8,5,6,5] ],

                        [[1,2,3,5],
                         [3,4,5,5],
                         [8,5,6,5] ]],
                       [[[1,2,3,5],
                         [3,4,5,5],
                         [8,5,6,5] ],

                        [[1,2,3,5],
                         [3,4,5,5],
                         [8,5,6,5] ]]
                       ])#TENSOR

print(f'{TENSOR.ndim} \n {TENSOR.shape} \n')

4 
 torch.Size([2, 2, 3, 4]) 



In [ ]:
TENSOR[0:,0:][0:,0:]

tensor([[[[1, 2, 3, 5],
          [3, 4, 5, 5],
          [8, 5, 6, 5]],

         [[1, 2, 3, 5],
          [3, 4, 5, 5],
          [8, 5, 6, 5]]],


        [[[1, 2, 3, 5],
          [3, 4, 5, 5],
          [8, 5, 6, 5]],

         [[1, 2, 3, 5],
          [3, 4, 5, 5],
          [8, 5, 6, 5]]]])

## Random tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers  - > look at data -> update random numbers -> look at data -> update random numbers`

Torch ramdom tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
#create a mramdom tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7241, 0.4775, 0.7466, 0.4479],
        [0.7660, 0.4089, 0.7947, 0.4347],
        [0.5902, 0.4455, 0.8497, 0.4467]])

In [ ]:
random_image_size_tensor = torch.rand(size=(3,224,224,3))#height, with, colour chanel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224, 3]), 4)

###Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3,4));zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4));ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

##Creating a range of tensors and tensors-like

In [ ]:
#Usetorch.range()
torch.range(0,10)

<ipython-input-15-11886aec79d0>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_ten = torch.arange(1,11);one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.arange(start = 0,end = 1000, step= 25)

tensor([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225, 250, 275, 300, 325,
        350, 375, 400, 425, 450, 475, 500, 525, 550, 575, 600, 625, 650, 675,
        700, 725, 750, 775, 800, 825, 850, 875, 900, 925, 950, 975])

In [ ]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten);ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
milzeros = torch.zeros_like(input = torch.arange(start =0, end=100, step=0.1));milzeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

##Tensor dataypes

In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

###Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & DeepLearning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right devide

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science


In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16);float_16_tensor#conversao de tipos

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long);int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

##Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tenosr.dtype`
2. Tensors not right shape - to get shape from a tensor , can use   `tensor.shape`
3. Tensors not on the right device - to get device frioma a tensor, can use `tensor.device`

In [ ]:
# Create a tensor

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9414, 0.8099, 0.3480, 0.3138],
        [0.2325, 0.7457, 0.1412, 0.1591],
        [0.7355, 0.0970, 0.0139, 0.2188]])

In [ ]:
# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9414, 0.8099, 0.3480, 0.3138],
        [0.2325, 0.7457, 0.1412, 0.1591],
        [0.7355, 0.0970, 0.0139, 0.2188]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulation Tensors

These operations are often a wonderful dance between:

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
#Create a Tensor and add ten to it
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
#Multiply Tensor by ten
tensor  * 10

tensor([10, 20, 30])

In [ ]:
#subtract Tensor 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
#Try out Pytorch in-build functions
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range (len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.03 ms, sys: 0 ns, total: 1.03 ms
Wall time: 957 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 377 µs, sys: 41 µs, total: 418 µs
Wall time: 289 µs


tensor(14)

There are two main rules that performing matrix mulçtiplication needs to start
1. The **inner dimensions**  must match:
* `(3,2) @ (3, 2 )` wont work
* `(2,3) @ (3, 2 )` will work
* `(3,2) @ (2, 3 )` will work
2. The resulting matrix has the shape of the **outer dimensions:**

* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @ (2, 3) -> (3, 3)`

In [ ]:
tensor @ tensor

tensor(14)

##One of the most comum errors in deep learning :shape errors

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

To fix our shape issues , we can manipulate the shape of one of our tensors using a **transpose.**
A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


##Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()#encontra e retorna a posição do menor valor no tensor

tensor(0)

In [ ]:
x.argmax()

tensor(9)

##Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remmoves all `1` dimensions from a tensor
* Unsqueeze - add `1` dimension to a target tensor
* Permute - Teturn a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


In [ ]:
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimensions
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[7., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[7.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [ ]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [ ]:
#Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 7
z, x

(tensor([[7., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([7., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0);x_stacked

tensor([[7., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1);x_stacked

tensor([[7., 7., 7., 7.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[7., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([7., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([7., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[7., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, with, colour_channels]

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"\n Origninal: {x_original.shape}")
print(f"New spermuted: {x_permuted.shape}") #[colour_channels, height, with,]


 Origninal: torch.Size([224, 224, 3])
New spermuted: torch.Size([3, 224, 224])


##Indexing (selecting data from tensors)

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Lets index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
#Lets index on the most inner bracket (last dimension)
x[0][0][0]


tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[0][1:][:1]

tensor([[4, 5, 6]])

In [ ]:
x[0 ,2, 2]

tensor(9)

In [ ]:
x[: ,:, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

Numpy is a popular scientific python numerical computing libary.
And /because of this, PyTorch has functionality to interact with it.
* Data in Numpy, want in PyTorch tensor - > `tensor.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy`

In [ ]:
#NumPy array topp tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)#warning when converting numpy -> pytorch pytorch reflects numpy's datatype of float64 unless  specified otherwise. You can converte using -> .type(torch.float32)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
#Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([ 5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor,tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

##Reproducibility (trying to take the random out of random)

In short:

`start with random numbers -> tensor operations -> try to make better (again and again and again)`

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

**random seed**


In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.5615, 0.3062, 0.0490, 0.2387],
        [0.0419, 0.0697, 0.6169, 0.4860],
        [0.6982, 0.2581, 0.0920, 0.5884]])

Tensor B:
tensor([[0.5453, 0.4587, 0.4449, 0.9822],
        [0.9219, 0.5457, 0.9786, 0.4740],
        [0.8089, 0.6984, 0.4538, 0.3677]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
#Let1s make some random but reproducible tensors

import torch
import random

# # Set the random seed
RANDOM_SEED=69 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8398, 0.8042, 0.1213, 0.5309],
        [0.6646, 0.4077, 0.0888, 0.2429],
        [0.7053, 0.6216, 0.9188, 0.0185]])

Tensor D:
tensor([[0.8398, 0.8042, 0.1213, 0.5309],
        [0.6646, 0.4077, 0.0888, 0.2429],
        [0.7053, 0.6216, 0.9188, 0.0185]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

from typing_extensions import get_overloads
##Runing tensors or pytorch object on GPU's

GPUs = fasteer computation on numbers, thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes to make everything hunky dory (get_overloads)

## 1. Getting GPU

1. Google Colab	Easy	Free to use, almost zero setup required, can share work with others as easy as a link	Doesn't save your data outputs, limited compute, subject to timeouts	Follow the Google Colab Guide.
https://colab.research.google.com/notebooks/gpu.ipynb


2. Use your own	Medium	Run everything locally on your own machine	GPUs aren't free, require upfront cost	Follow the PyTorch installation guidelines.
https://pytorch.org/get-started/locally/


3. Cloud computing (AWS, GCP, Azure)	Medium-Hard	Small upfront cost, access to almost infinite compute	Can get expensive if running continually, takes some time ot setup right	Follow the PyTorch installation guidelines.
https://pytorch.org/get-started/cloud-partners/

##2. Check for GPU acess with Pytorch





In [ ]:
import torch
torch.cuda.is_available()

False

In [ ]:
#Setup mdevice agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Cont number of devices
torch.cuda.device_count()

1

##Settings agnostic device codes

## 3. Putting tensors (and models) on the GPU

The reason we want outr tensors/models oon the GPU is because using a GPU results in Faster computations.

In [ ]:
# create a tensor
tensor = torch.tensor([1,2,3], device="cpu")

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if avaiable)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

###4. Moving tensors back to the CPU

In [ ]:
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
#To fix the GPU tensor
tensor_back_on_gpu = tensor_on_gpu.cpu().numpy()

tensor_back_on_gpu

array([1, 2, 3])

##Exercises

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises