In [1]:
import torch 
import numpy as np

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [11]:
import torch
# Create random tensor
x = torch.rand([7,7])

In [12]:
x.shape, x.mean()

(torch.Size([7, 7]), tensor(0.4785))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [13]:
# Create another random tensor
y = torch.rand(1,7)

# Perform matrix multiplication 

z = x @ y.T

z

tensor([[0.8371],
        [1.4218],
        [1.3807],
        [2.2673],
        [1.9052],
        [2.3668],
        [2.2041]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [14]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x= torch.rand([7,7])
y = torch.rand([1,7])

# Matrix multiply tensors
z = x @ y.T

print(f"""Matrix x : {x} {x.shape}\n
          Matrix y : {y} {y.shape} and Tranpose {y.T.shape}\n
          Matrix z : {z} {z.shape}\n""")

Matrix x : tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]) torch.Size([7, 7])

          Matrix y : tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]) torch.Size([1, 7]) and Tranpose torch.Size([7, 1])

          Matrix z : tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])



### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU
device = "cuda"
torch.cuda.is_available()

torch.cuda.manual_seed(1234)

#The cuda manual seed should be set if you want to have reproducible results when using random generation on the gpu, for example if you do 
h= torch.cuda.FloatTensor(100).uniform_()





### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [17]:
# Set random seed
torch.manual_seed(1234)


# Check for access to GPU
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
print(torch.cuda.device_count())

# Create two random tensors on GPU
r1 = torch.rand([2,3],device = device)
r2 = torch.rand([2,3],device = device)

1


In [18]:
print(f"r1 : {r1}\nr2: {r2} \n")

r1 : tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
r2: tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0') 




### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [19]:
# Perform matmul on tensor_A and tensor_B
r3 = r1 @ r2.T
print(f'matrix multiplication: r1 @ r2.T \n {r3}')

matrix multiplication: r1 @ r2.T 
 tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
print(r3.max())
# Find min
print(r3.min())

tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [42]:
import numpy as np

# Find arg max
n_r3 = r3.cpu().numpy()
print(f'posição do maior valor :{np.argmax(n_r3,axis=0)}')

# Find arg min
print(f'posição do menor valor :{np.argmin(n_r3,axis=0)}')


posição do menor valor :[1 0]
posição do menor valor :[0 1]



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [44]:
# Set seed
torch.manual_seed(7)

# Create random tensor
oneten = torch.rand(1,1,1,7)

# Remove single dimensions
ten = oneten.squeeze()

# Print out tensors and their shapes
print(f"""muitas dimensoes {oneten} {oneten.shape}\n
          uma dimensao {ten} {ten.shape} """)

muitas dimensoes tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071]]]]) torch.Size([1, 1, 1, 7])

          uma dimensao tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071]) torch.Size([7]) 
